version: '3'

services:
  samba:
    build: .
    #ports:
      #- "137:137/udp"
      #- "138:138/udp"
      #- "139:139"
      #- "445:445"
    volumes:
      - ./setting/etc/samba:/etc/samba
      - ./setting/var/lib/samba:/var/lib/samba
      - ./setting/var/run/samba:/var/run/samba
      - ./data:/data
      - ./log:/var/log/samba

